# Use NVIDIA's PyTorch container as the base
FROM nvcr.io/nvidia/pytorch:23.06-py3

# Set the working directory
WORKDIR /app

# Install additional dependencies
RUN pip install --upgrade pip \
    && pip install joblib transformers datasets scikit-learn accelerate

# Copy the training script to the container
COPY model/train_model.py /app/train_model.py

# Set the entry point for the container
ENTRYPOINT ["python", "/app/train_model.py"]
