apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.4.1-base-ubuntu20.04
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
