apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 2Gi  # Adjust the size as necessary
  accessModes:
    - ReadWriteOnce
  hostPath:  # Using hostPath to specify local storage
    path: /mnt/data/model-storage  # Change this to a valid path on your host machine

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Must match the PV size

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
      - name: model-training
        image: dockerhub88/model-trainer:latest
        resources:
          limits:
            cpu: "2"  # You can specify a CPU limit instead, for example
        volumeMounts:
        - name: model-storage
          mountPath: /app/distilbert_model  # Persistent storage for the model
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc  # A Persistent Volume Claim (PVC) for saving the model
