apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres  # Path on the host machine for data storage
